### ISSUE TITLE
Installation attempt fails

### ISSUE THREAD

**Issue by johnblommers** [ONLYOFFICE/plugin-typograf#11]
The following does not work. There are no warnings and the plugin does not become available.

1. Download this repository as a zip file.
2. Change the extensions from zip to plugin
3. Launch OnlyOffice Desktop Editor and open a document
4. Plugins tab
5. Settings
6. Add plugin
7. Locate `plugin-typograf-master.plugin` \
8. Click Open
9. Typograf does not appear in the list of installed plugins

Please document how this particular plugin should be installed from this archive.

**Comment by ShockwaveNN** [comment]
You should not download repository as as zip, but clone it and zip result, so folders like `license` and files like `config.json` will be at root of archive

Because while downloading it as zip - there will be `plugin-typograf-master` folder at root as archive - this is incorrect structure

**Comment by amokmen** [comment]
Also just lost time to understand that if inside archive is folder - there would be no magic.

I think you should do smth with this situation and I see 2 ways:
1) create checking for folder inside an archive in code of desktop editors
or
2) use GitHub Actions to autocreate release with ready-to-use downloadable archive.

**Comment by ShockwaveNN** [comment]
@amokmen Yeah, we working on it, fail more gracefully if plugin cannot be installed. There is issue 48925 in our private issue tracker

**Comment by amokmen** [comment]
Correct error showing always good option, but this is not solving this issue :)

If use GitHub Actions and Ubuntu 18.04.5 virtual machine, there would be already [preinstalled](https://github.com/actions/virtual-environments/blob/ubuntu18/20200920.1/images/linux/Ubuntu1804-README.md) "7-Zip" and "zip" tools. So, simple creating an archive would be easy task.

Could you write YAML config file or I should help?

**Comment by ShockwaveNN** [comment]
@amokmen Sorry, I'm just a QA specifalits.
 It's up to @trofim24 and @agolybev to decide - will we start using Github Actions to releasing plugins

**Comment by depascalis** [comment]
You can still download the repository as a zip!
1. Unzip the downloaded repository
2. Go to root directory
3. Select all files and folders and archive it
4. Rename the zip-file to `typograf-v#.#.#.plugin`
5. Install as usual

**Comment by catbasilio** [comment]
[Fixed](https://github.com/ONLYOFFICE/plugin-typograf/releases/tag/v1.0.0)
