### ISSUE TITLE
Russian language. Comma in such case -> "Проблема , с запятой" would be corrected, but in strange way.

### ISSUE THREAD

**Issue by amokmen** [ONLYOFFICE/plugin-typograf#12]
Just installed plugin at "ONLYOFFICE Desktop Editors версия 6.1.0.90"

Result after correction:
```
Проблема<span class="typograf-oa-comma">,</span><span class="typograf-oa-comma-sp"> </span>с запятой
```

**Comment by Rita-Bubnova** [comment]
Hello, @amokmen.
Could you describe the steps to reproduce the problem?

**Comment by amokmen** [comment]
1. Open new document file in desktop editor.
2. Install plugin.
3. In plugin's options choose 'Russian' locale.
4. Check 'Punctuation' checkbox & 'Hanging punctuation' & 'Space and line ending' & all sub-checkboxes active also.
5. Paste my line.
6. Choose my line by marking.
7. Press 'Correct text'

Also interesting, that if check only 'Hanging punctuation' - this hanging comma would not be corrected at all!

**Comment by Rita-Bubnova** [comment]
Which line do you paste in step 5? And which result do you want?

**Comment by amokmen** [comment]
I paste line from heading ^^: "Проблема , с запятой"
I wanted this: "Проблема, с запятой"

**Comment by Rita-Bubnova** [comment]
I can confirm - this is bug, issue 48936 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
Now we aren't able to fully resolve this issue because the document editor does not support "Hanging punctuation".

**Comment by catbasilio** [comment]
[Fixed](https://github.com/ONLYOFFICE/plugin-typograf/commit/3599f0c49f733e39448d5edadbb791efcc340138)
